package main

import (
	"net/http"

	"github.com/akrylysov/algnhsa"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	"github.com/vifor/recetop-activity-service/api" // Import our generated api package
)

// Server is our custom struct which will hold any dependencies and implement our API.
type Server struct {
	// In the future, you could add dependencies like a database connection here.
}

// Ensure our Server struct satisfies the generated ServerInterface.
// The compiler will error here if we don't implement all the interface's methods.
var _ api.ServerInterface = (*Server)(nil)

// HealthCheck implements the `healthCheck` operation defined in our openapi.yaml
func (s *Server) HealthCheck(ctx echo.Context) error {
	// This is our business logic from before.
	response := api.HealthStatus{
		Status:  "UP",
		Message: "Go serverless with OpenAPI spec!", // Updated message!
	}
	return ctx.JSON(http.StatusOK, response)
}

func main() {
	// Create an instance of our server
	s := &Server{}

	// Create a new Echo instance
	e := echo.New()

	// Add standard middleware
	e.Use(middleware.Logger())
	e.Use(middleware.Recover())

	// Register our server as the handler for the API.
	// The `RegisterHandlers` function was also generated by oapi-codegen.
	api.RegisterHandlers(e, s)

	// The algnhsa library is an "adapter". It starts our Echo server
	// and translates AWS Lambda events into standard HTTP requests that Echo can understand.
	algnhsa.ListenAndServe(e, nil)
}
